apiVersion: v1
kind: Service
metadata:
  name: {{ include "vocabs.fullname" . }}-fuseki
  labels:
    {{- include "vocabs.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fuseki.service.port }}
      targetPort: http
  selector:
    {{- include "vocabs.selector" . | nindent 4 }}
    app.kubernetes.io/component: fuseki
