{{- $i := .Values.fuseki.ingress -}}
{{- if $i.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vocabs.fullname" . }}-fuseki-admin
  labels:
    {{- include "vocabs.labels" . | nindent 4 }}
  annotations:
    {{- toYaml $i.annotations | nindent 4 }}
spec:
  {{- with $i.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- if $i.tls.enabled }}
  tls:
    - hosts: [{{ required "Fuseki ingress host is required" $i.host | quote }}]
      secretName: {{ required "TLS secretName is required when Fuseki TLS is enabled" $i.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ required "Fuseki ingress host is required" $i.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vocabs.fullname" . }}-fuseki
                port:
                  number: {{ .Values.fuseki.service.port }}
{{- end }}