apiVersion: v1
kind: Service
metadata:
  name: {{ include "vocabs.fullname" . }}-fuseki-headless
  labels:
    {{- include "vocabs.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - {name: http, port: 3030, targetPort: http}
  selector:
    {{- include "vocabs.selector" . | nindent 4 }}
    app.kubernetes.io/component: fuseki
