{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vocabs.sa" . }}
  labels:
    {{- include "vocabs.labels" . | nindent 4 }}
  annotations:
    {{- toYaml (merge .Values.serviceAccount.annotations .Values.commonAnnotations) | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
