apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vocabs.fullname" . }}-vinyl
  labels:
    {{- include "vocabs.labels" . | nindent 4 }}
    app.kubernetes.io/component: vinyl
data:
  default.vcl: |
    {{- tpl .Values.vinyl.vclConfig . | nindent 4 }}
